- name: Install Wazuh Agent
  hosts: all
  roles:
    - wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: 10.10.10.238
        port: 1514
        protocol: udp
        api_port: 55000
        api_proto: 'http'
        api_user: wazuh
    wazuh_agent_authd:
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'