- hosts: wazuh
  roles:
    - role: wazuh/ansible-wazuh-manager
    - {role: wazuh/ansible-filebeat, filebeat_output_logstash_hosts: '10.10.10.237:5000'}
- hosts: elastic
  roles:
    - {role: elastic-stack/ansible-elasticsearch, elasticsearch_network_host: 'localhost'}
    - {role: elastic-stack/ansible-logstash, logstash_input_beats: true, elasticsearch_network_host: 'localhost'}
    - {role: elastic-stack/ansible-kibana, elasticsearch_network_host: 'localhost'}
